### ISSUE TITLE
Is it possible to communicate without directline? directly?

### ISSUE THREAD

**Issue by amitbend** [Capgemini-AIE/bot-framework-actions-on-google#26]
As the pricing of the Directline channel is pretty high, I was wondering if it's possible to communicate with the module directly

**Comment by daniel-cotton** [comment]
Hey @amitbend - definitely possible, though currently there's not any plans to adapt this module to that use-case as there's a bit more to be handled (generating conversation ID's .etc) 

If directline isn't the protocol you'd like to use, I'd advocate creating a replacement bridge that handles the direct communication and keeping modules such as this over directline for separation of concerns.

Closing this as I think it's out of the scope of this module, writing a directline proxy may be something I'll personally look at in future, but it's not directly related to this project.
