### ISSUE TITLE
Are we supposed to use firebase in this process? 

### ISSUE THREAD

**Issue by mdmjg** [Capgemini-AIE/bot-framework-actions-on-google#28]
I am not sure if we should use firebase, as it would create a new functions folder with another index.js file. What should we put in this file?

**Comment by daniel-cotton** [comment]
Hey @mdmjg - Any NodeJS runtime will work with this module (including firebase functions!). 

All you would need to do is follow the process you've currently followed, generating a sample function (index.js).

Once this is done, structure your function as according to this example
https://github.com/jthegedus/firebase-gcp-examples/tree/master/firebase-functions-express

That shows how to use Express with Firebase Functions. Once this is done, follow the "Demo" folder/ Readme.md of this project to integrate the module with the express server setup on the function.

Hope this helps!

(Closing this as it's sort of out of the scope of this module)
